#!/bin/bash

<< COMMENT

    USAGE : 
        ./ViroScan [-h] -f <fastq_directory> -v <virus> -s <se|pe> -o <output_directory> 
        [-x <reference_filter_out>] [-u <1|2>] [-p <threads>] [-b <\"breseq_options\">] [-t <threshold>]
    DESCRIPTION : 
        ViroScan is an automated pipeline that eliminate reads not of interest according to a reference (filter-out) 
        and identify viruses present (filter-in)
    PREREQUISITE : 
        * Scripts :
            - bash file config.sh into the config directory
            - python script write_output_tables.py into the src directory
        * Tools :
            - Bowtie2 (http://bowtie-bio.sourceforge.net/bowtie2/index.shtml)
            - Python3 (https://www.python.org/downloads/)
            - R (https://www.r-project.org/)
            - breseq (https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/)
            - Samtools (http://www.htslib.org/)
            NB : Bowtie2 and R are used by breseq
        * Data :
            - Viruses references in Genbank format into the directory data
        * Python modules :
            - argparse
            - json
            - re
            - sys
    AUTHOR :
        Sarah BOUZIDI
        Engineer in bioinformatics
        Centre National de la Recherche Scientifique (CNRS)
        Team Virostyle, Laboratory MIVEGEC, IRD, Montpellier
        
COMMENT

# Exit if a command exits with a non zero status
set -e



########################################################################################
#                                    CONFIGURATION
########################################################################################

# Check if config file exist and import it
if [ ! -f "$(dirname $0)"/config/config.sh ]
then
	echo -e "ViroScan: error : The config file "$(dirname $0)"/config/config.sh used by ViroScan doesn't exist"
	exit
else
    source "$(dirname $0)"/config/config.sh
fi



########################################################################################
#                                    COMMAND LINE
########################################################################################

# Function to print the header in the shell
function header(){
    printf "\nViroScan\n"
    printf "2023 - Sarah Bouzidi <sarah.bouzidi@ird.fr>\n"
}

### USAGE OF THE PIPELINE
function usage(){
    header
    printf "\nUsage :\n"
	printf "./ViroScan [-h] -f <fastq_directory> -v <virus> -s <se|pe> -o <output_directory> [-x <reference_filter_out>] [-u <1|2>] [-p <threads>] [-b <\"breseq_options\">] [-t <threshold>]\n"
    
    printf "\nAbout :\n"
    printf "ViroScan is an automated pipeline that eliminate reads not of interest according to a reference (filter-out) and identify viruses present (filter-in)\n"
	
    printf "\nPrerequisite :\n"
    printf "\t- Bowtie2 (http://bowtie-bio.sourceforge.net/bowtie2/index.shtml)\n"
    printf "\t- Python3 (https://www.python.org/downloads/)\n"
    printf "\t- R (https://www.r-project.org/)\n"
    printf "\t- breseq (https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/)\n"
    printf "\t- Samtools (http://www.htslib.org/)\n"
    
    printf "\nMandatory options :\n"
	printf "\t-f                 : Path of the FASTQ file(s) to analyse. 
                             In case of paired-end, make sure your
                             files have '_R1*paired', 
                             '_R2*paired', '_R1*unpaired'
                             '_R2*unpaired' patterns. The underscore is
                             essential. 
                             '.fastq', '.fq' and '.gz'
                             extensions are accepted ;\n\n"
    
    printf "\t-v                 : Virus to use to find the closest viral sequence.
                             Available :
                             - adenoviridae
                             - adomavirus
                             - anelloviridae
                             - circoviridae
                             - herpesvirales
                             - papillomavirus
                             - parvoviridae
                             - polyomavirus 
                             - all
                             If you want to use your own viral sequences, add
                             a '.gbk' file (Genbank format) into the data 
                             directory. Make sure that the name is
                             'virus.gbk'. You can zip it to limit the space
                             used. In this case, the name of the zip file must 
                             be 'virus.gbk.zip' ;\n\n"
    printf "\t-s                 : Single-end or paired-end data to analyse ;\n\n"
	
    printf "\t-o                 : Path of the output directory where results will 
                             be written. 
                             If the directory doesn't exist, it will be created ;\n"
    
    printf "\nSupplementary options :\n"
    printf "\t-x                 : Path of reference indexed and the pattern name 
                             of indexes to perform filter-out. Make sure the reference
                             was indexed by Bowtie. So, it's means files have to
                             finished by '.bt2' ;\n\n"

    printf "\t-u                 : Number of unpaired files.  
                             Default 2 ;\n\n"

	printf "\t-p                 : Number of threads to use. 
                             Default 1 ;\n\n"
    
    printf "\t-b                 : breseq options. 
                             Default \"-p\".
                             Make sure if you want to change default options to
                             input the value with quotation marks.
                             Warning : Do not inform option -j ;\n\n"
    
    printf "\t-t                 : Threshold value of the minimum alignment 
                             percentage to report. 
                             Default 5 ;\n\n"
    printf "\t-h                 : Help ;\n" 

    printf "\nExample :\n"
    printf "/home/user/ViroScan/ViroScan -f /home/user/dir_of_data_to_analyse -v papillomavirus -s pe -o /home/user/data_analysed -x /home/user/GRCh38_noalt_as/GRCh38_noalt_as -u 1 -p 12 -b "--no-junction-prediction"\n"
}

# Print usage if there is just the name of the script in command line
if [ $# -eq 0 ]
then
	usage
	exit
fi


### ARGS
while getopts ":f:v:s:o:x:u:p:b:t:h" option; 
do
    case "${option}" in
        f)
            f=${OPTARG};;
        v)
            v=${OPTARG};;
        s)
            s=${OPTARG};;
        o)
            o=${OPTARG};;
        x)
            REFINDEXED=${OPTARG};;
        u)
            NBRUNPAIRED=${OPTARG};;
        p)
            THREADS=${OPTARG};;
        b)
            BRESEQ_OPTIONS=${OPTARG};;
        t)
            THRESHOLD=${OPTARG};;
        h)
            usage
            exit;;
        *)
            usage;;
    esac
done
shift $((OPTIND-1))



########################################################################################
#                                    VERIFICATION 
########################################################################################

### COMMAND LINE & VALUES
# Check if mandatory arguments exists
if [ -z "${f}" ] || [ -z "${v}" ] || [ -z "${s}" ] || [ -z "${o}" ]; 
then
    echo -e "ViroScan: warning : You must enter all the mandatory arguments"
    echo -e "Use \"ViroScan -h\" to see all command-line options."
    exit
fi

# Check if the input directory exist
if [ ! -d "${f}" ]
then
	echo -e "ViroScan: error : The FASTQ directory ${f} doesn't exist"
	exit
fi

# Check if there is at least one FASTQ file into the dir
NBFASTQFILE=`ls -1 "${f}"/*.f*q* 2>/dev/null | wc -l`
if [ $NBFASTQFILE = 0 ]
then 
	echo -e "ViroScan: warning : There is no FASTQ file into the directory ${f}"
	exit
fi 

# Check if the reference file exist
if [ ! -f "$DIRDATA/${v}"* ]
then
	echo -e "ViroScan: error : The reference file of the virus $virus doesn't exist"
	exit
fi

# Check if the read type is input correctly
if [[ ${s} != "se" && ${s} != "pe" ]]
then
    echo -e "ViroScan: warning : For the option -s, you have to write se or pe"
    exit
fi

# Check if the number of unpaired files is input correctly
if [[ $NBRUNPAIRED != 1 && $NBRUNPAIRED != 2 ]]
then
    echo -e "ViroScan: warning : For the option -u, you have to write 1 or 2"
    exit
fi

# Check if there are at least one FASTQ _R1/_R2 and as many R1 files as there are R2
if [ "${s}" == "pe" ]
then
    NBFASTQFILER1=`ls -1 "${f}"/*_R1* 2>/dev/null | wc -l`
    NBFASTQFILER2=`ls -1 "${f}"/*_R2* 2>/dev/null | wc -l`
    if [ $NBFASTQFILER1 = 0 ]
    then
        echo -e "ViroScan: warning : : There is not paired-end FASTQ files, according to _R1 and _R2 pattern name"
        exit
    fi
    if [ $NBFASTQFILER1 != $NBFASTQFILER2 ]
    then
        echo -e "ViroScan: warning : : There are not as many FASTQ R1 files as there are FASTQ R2 files"
        echo -e "Number of R1 files : $NBFASTQFILER1, R2 files : $NBFASTQFILER2"
        exit
    fi
fi

# Check if the value of threads is an integer
if ! [[ $THREADS =~ ^[0-9]+$ ]]
then 
    echo -e "ViroScan: warning : The value of threads informed must be an integer"
    exit
fi

# Check if the value of threshold is an float
if ! [[ $THRESHOLD =~ ^[0-9]+([.][0-9]+)?$ ]]
then 
    echo -e "ViroScan: warning : The value of threshold informed must be a float"
    exit
fi


### CONFIG FILE
# Check if the directory of the scripts exist
if [ ! -d "$DIRSCRIPTS" ]
then
	echo -e "ViroScan: error : The directory of the scripts "$DIRSCRIPTS" used by ViroScan doesn't exist"
	exit
fi

# Check if the scripts exist
if [ ! -f "$DIRSCRIPTS"/write_output_tables.py ]
then
	echo -e "ViroScan: error : The script "$DIRSCRIPTS"/write_output_tables.py used by ViroScan doesn't exist"
	exit
fi

# Check if the directory of the data exist
if [ ! -d "$DIRDATA" ]
then
	echo -e "ViroScan: error : The directory of the data "$DIRDATA" used by ViroScan doesn't exist"
	exit
fi

# Check if, according to the value in the config file and if var is not empty, there is reference indexed
if [ ! -z "$REFINDEXED" ]
then
    NBINDEXFILE=`ls -1 "$REFINDEXED"*.bt2 2>/dev/null | wc -l`
    if [ $NBINDEXFILE = 0 ]
    then 
    	echo -e "ViroScan: error : There is no index file(s) $(basename $REFINDEXED) into the directory of the data"
    	exit
    fi 
fi

# Check if tools are available
if ! [ -x "$(command -v "$BOWTIE" --version)" ]
then
    echo -e "ViroScan: error : Bowtie2 is needed to use ViroScan"
	exit
fi
if ! [ -x "$(command -v "$BRESEQ" --version)" ]
then
    echo -e "ViroScan: error : breseq is needed to use ViroScan"
	exit
fi
if ! [ -x "$(command -v "$SAMTOOLS" --version)" ]
then
    echo -e "ViroScan: error : samtools is needed to use ViroScan"
	exit
fi
if ! [ -x "$(command -v R --version)" ]
then
    echo -e "ViroScan: error : R is needed to use ViroScan"
	exit
fi
if ! [ -x "$(command -v python3 --version)" ]
then
    echo -e "ViroScan: error : Python3 is needed to use ViroScan"
	exit
fi



########################################################################################
#                                    INITIALIZATION 
########################################################################################

# ViroScan "start" so print the header and the command-line used
echo -e "\n================================================================================"

header

echo -e "\nViroScan : Start with the command-line :"
if [ ! -z "$REFINDEXED" ]
then
    echo -e "$(dirname $0)/ViroScan -f ${f} -v ${v} -s ${s} -o ${o} -x ${REFINDEXED} -u ${NBRUNPAIRED} -p ${THREADS} -b \"${BRESEQ_OPTIONS}\" -t ${THRESHOLD}"
else
    echo -e "$(dirname $0)/ViroScan -f ${f} -v ${v} -s ${s} -o ${o} -u ${NBRUNPAIRED} -p ${THREADS} -b \"${BRESEQ_OPTIONS}\" -t ${THRESHOLD}"
fi

echo -e "\n================================================================================\n"


### REFERENCE
# Unzip reference file to use into analysis if it compressed
if [ -f "$DIRDATA"/"${v}".gbk.zip ]
then
    unzip -o "$DIRDATA"/"${v}".gbk.zip -d "$DIRDATA"
fi

### OUTPUT
# Create the output directory of results if he doesn't exists
mkdir -p "${o}"

# Create a log files directory into the output directory of results
mkdir -p "${o}"/log

# Create a temporary directory
mkdir -p "${o}"/tmp

# Create directory with tool's output and evidences into the output directory of results
mkdir -p "${o}"/output
mkdir -p "${o}"/output/data
if [ ! -z "$REFINDEXED" ]
then
    mkdir -p "${o}"/output/data/filter_out
    mkdir -p "${o}"/output/data/filter_out/matched
    mkdir -p "${o}"/output/data/filter_out/unmatched
fi
mkdir -p "${o}"/output/data/filter_in
mkdir -p "${o}"/output/evidences
mkdir -p "${o}"/output/analysis


### FASTQ NAMES
# Create an array with all fastq file names
declare -a FASTQ_NAMES
for fastq_file in "${f}"/*.f*q*
	do
		fastq_file_without_path=${fastq_file##*/}
		fastq_file_without_extension=${fastq_file_without_path%.f*q*}
        # Single-end
        if [ "${s}" == "se" ]
        then 
            # Save file name
            FASTQ_NAMES+=("$fastq_file_without_extension")
        # Paired-end
        elif [ "${s}" == "pe" ]
        then
            if [[ $fastq_file_without_extension == *"_R"* ]]
            then
                # Load file name without extension _R (pattern for R1 and R2)
                fastq_file_without_read_ext=${fastq_file_without_extension%"_R"*}
                # Look if the file name doesn't exist in the array (avoid duplicates)
                if [[ ! "${FASTQ_NAMES[@]}" =~ "${fastq_file_without_read_ext}" ]]
                then
                    # Save it
                    FASTQ_NAMES+=("$fastq_file_without_read_ext")
                fi
            fi
        fi
	done

# Sort the array alphanumerically
IFS=$'\n' FASTQ_NAMES=($(sort -V <<<"${FASTQ_NAMES[*]}"))
unset IFS



#########################################################################################
#                                    ANALYSIS
#########################################################################################

### SINGLE-END
if [ "${s}" == "se" ]
then
    
    for fastq_name in ${FASTQ_NAMES[@]}
    do 

        echo -e "\n------------------  $fastq_name  ---------------------"
        
        # Retieve the path and the exact name of the input file 
        inputfile=`find ${f} -type f -name "$fastq_name"*.f*q*`
        
        # If a filter-out step is launch
        if [ ! -z "$REFINDEXED" ]
        then
            echo -e "*** ELIMINATE READS NOT OF INTEREST (FILTER-OUT)\n"
            # Run Bowtie2 to aligned input reads against the genome indexed
            "$BOWTIE" -x "$REFINDEXED" -p "$THREADS" -U "$inputfile" -S "${o}"/tmp/"$fastq_name"_aligned_against_genome.sam --al-gz "${o}"/output/data/filter_out/matched/"$fastq_name".fq.gz --un-gz "${o}"/output/data/filter_out/unmatched/"$fastq_name".fq.gz &>> "${o}"/log/"$fastq_name""_bowtie2.log"
            # Remove SAM file into the tmp directory
            rm "${o}"/tmp/*
            echo -e "*** IDENTIFY VIRUSES PRESENT (FILTER-IN)\n"
            # Run breseq to aligned and analysed reads of interest, ie reads not aligned against the genome indexed
            "$BRESEQ" -r "$DIRDATA"/"${v}".gbk $BRESEQ_OPTIONS -j "$THREADS" "${o}"/output/data/filter_out/unmatched/"$fastq_name".fq.gz -o "${o}"/output/analysis/"$fastq_name" &>> "${o}"/log/"$fastq_name""_breseq.log"
        
        # If a filter-out step isn't launch
        else
            echo -e "*** IDENTIFY VIRUSES PRESENT (FILTER-IN)\n"
            # Run breseq to aligned and analysed reads
            "$BRESEQ" -r "$DIRDATA"/"${v}".gbk $BRESEQ_OPTIONS -j "$THREADS" "$inputfile" -o "${o}"/output/analysis/"$fastq_name" &>> "${o}"/log/"$fastq_name""_breseq.log"
        fi

        # Remove useless dir of breseq output
        rm -r "${o}"/output/analysis/"$fastq_name"/0*
        
        echo -e "*** REPORT NUMBER OF TOTAL READS ALIGNED AND PERCENT OF READS FROM EACH VIRUS IDENTIFIED\n"
        # Run python script to report percent of reads of interest aligned, according to the treshold, into a table and the number of reads input aligned
        python3 "$DIRSCRIPTS"/write_output_tables.py "$fastq_name" "${o}"/output/analysis/"$fastq_name"/output/summary.json "${o}"/output/evidences/refs.percents.txt "$THRESHOLD" --output_counts "${o}"/output/evidences/filterin.counts.txt
    
    done

    echo -e "\n------------------  All samples  ---------------------"

    echo -e "*** REPORT COVERAGE FOR EACH VIRUS IDENTIFIED AND RETRIEVE VIRAL READS ALIGNED\n"
    # For each line from the file refs.percents.txt where there are samples and references detected
    while IFS=$'\t' read -r sample reference percent
    do
        # Run samtools to retrieve from sample alignment against reference   
        "$SAMTOOLS" view -h "${o}"/output/analysis/"$sample"/data/reference.bam "$reference" > "${o}"/tmp/"$sample"_"$reference".sam

        # Calcul metrics about coverage
        "$SAMTOOLS" depth -a "${o}"/tmp/"$sample"_"$reference".sam | awk 'NR==1 {maxcov=0;mincov=1}; NR>1 {sumcov+=$3; if(mincov>$3) mincov=$3; if(maxcov<$3) maxcov=$3; if($3>2) {covmoretwo++}; if($3>20) {covmoretwenty++}; cnt = NR} END {print spl"\t"ref"\t"sumcov/(cnt-1)"\t"mincov"\t"maxcov"\t"covmoretwo"\t"covmoretwenty}' spl="$sample" ref="$reference" >> "${o}"/output/evidences/refs.coverage.txt

        # Retrieve reads aligned and save them into a fastq file
        "$SAMTOOLS" fastq -@ "$THREADS" -0 "${o}"/output/data/filter_in/"$sample"_"$reference".fastq.gz "${o}"/tmp/"$sample"_"$reference".sam  
        rm "${o}"/tmp/"$sample"_"$reference".sam
    done < "${o}"/output/evidences/refs.percents.txt

    # To finalize, add the header to output files
    sed -i '1 i\SAMPLE\tNBR_READS_TO_ALIGN\tNBR_TOTAL_READS_ALIGNED' "${o}"/output/evidences/filterin.counts.txt
    sed -i '1 i\SAMPLE\tREFERENCE\tPERCENT_OF_READS_ALIGNED' "${o}"/output/evidences/refs.percents.txt 
    sed -i '1 i\SAMPLE\tREFERENCE\tAVERAGE_DEPTH\tMIN_DEPTH\tMAX_DEPTH\tBASES_COVERED_AT_LEAST_TWICE\tBASES_COVERED_AT_LEAST_TWENTY_TIMES' "${o}"/output/evidences/refs.coverage.txt
fi


### PAIRED-END
if [ "${s}" == "pe" ]
then
    
    for fastq_name in ${FASTQ_NAMES[@]}
    do 

        echo -e "\n------------------  $fastq_name  ---------------------"
        
        # Retieve the path and the exact name of the input files paired
        input_R1_paired_file=`find ${f} -type f \( -name "$fastq_name"*R1*paired*.f*q* ! -name "$fastq_name"*R1*unpaired*.f*q* \)`
        input_R2_paired_file=`find ${f} -type f \( -name "$fastq_name"*R2*paired*.f*q* ! -name "$fastq_name"*R2*unpaired*.f*q* \)`
        # Retrieve the path and the exact name of the input file(s) unpaired
        if [ "$NBRUNPAIRED" == 1 ]
        then
            input_unpaired_file=`find ${f} -type f -name "$fastq_name"*unpaired*.f*q*`
        else
            input_R1_unpaired_file=`find ${f} -type f -name "$fastq_name"*R1*unpaired*.f*q*`
            input_R2_unpaired_file=`find ${f} -type f -name "$fastq_name"*R2*unpaired*.f*q*`
        fi
        
        #If a filter-out step is launch
        if [ ! -z "$REFINDEXED" ]
        then
            # In case of only one unpaired file
            if [ "$NBRUNPAIRED" == 1 ]
            then
                echo -e "*** ELIMINATE READS NOT OF INTEREST (FILTER-OUT)\n"
                # Run Bowtie2 to aligned input reads against the genome indexed
                "$BOWTIE" -x "$REFINDEXED" -p "$THREADS" -1 "$input_R1_paired_file" -2 "$input_R2_paired_file" -U "$input_unpaired_file" -S "${o}"/tmp/"$fastq_name"_aligned_against_genome.sam --al-gz "${o}"/output/data/filter_out/matched/"$fastq_name".unpaired.fq.gz --un-gz "${o}"/output/data/filter_out/unmatched/"$fastq_name".unpaired.fq.gz --al-conc-gz "${o}"/output/data/filter_out/matched/"$fastq_name"_R%.paired.fq.gz --un-conc-gz "${o}"/output/data/filter_out/unmatched/"$fastq_name"_R%.paired.fq.gz &>> "${o}"/log/"$fastq_name""_bowtie2.log"
            
            # In case of two unpaired files
            else
                echo -e "*** ELIMINATE READS NOT OF INTEREST (FILTER-OUT)\n"
                "$BOWTIE" -x "$REFINDEXED" -p "$THREADS" -1 "$input_R1_paired_file" -2 "$input_R2_paired_file" -U "$input_R1_unpaired_file","$input_R2_unpaired_file" -S "${o}"/tmp/"$fastq_name"_aligned_against_genome.sam --al-gz "${o}"/output/data/filter_out/matched/"$fastq_name".unpaired.fq.gz --un-gz "${o}"/output/data/filter_out/unmatched/"$fastq_name".unpaired.fq.gz --al-conc-gz "${o}"/output/data/filter_out/matched/"$fastq_name"_R%.paired.fq.gz --un-conc-gz "${o}"/output/data/filter_out/unmatched/"$fastq_name"_R%.paired.fq.gz &>> "${o}"/log/"$fastq_name""_bowtie2.log"
            fi

            # Remove SAM file into the tmp directory
            rm "${o}"/tmp/*
            echo -e "*** IDENTIFY VIRUSES PRESENT (FILTER-IN)\n"
            # Run breseq to aligned and analysed reads of interest, ie reads not aligned against the reference genome indexed
            "$BRESEQ" -r "$DIRDATA"/"${v}".gbk $BRESEQ_OPTIONS -j "$THREADS" "${o}"/output/data/filter_out/unmatched/"$fastq_name"_R1.paired.fq.gz "${o}"/output/data/filter_out/unmatched/"$fastq_name"_R2.paired.fq.gz "${o}"/output/data/filter_out/unmatched/"$fastq_name".unpaired.fq.gz -o "${o}"/output/analysis/"$fastq_name" &>> "${o}"/log/"$fastq_name""_breseq.log"
        
        # If a filter-out step isn't launch
        else
            # In case of only one unpaired file
            if [ "$NBRUNPAIRED" == 1 ]
            then
                echo -e "*** IDENTIFY VIRUSES PRESENT (FILTER-IN)\n"
                # Run breseq to aligned and analysed reads
                "$BRESEQ" -r "$DIRDATA"/"${v}".gbk $BRESEQ_OPTIONS -j "$THREADS" "$input_R1_paired_file" "$input_R2_paired_file" "$input_unpaired_file" -o "${o}"/output/analysis/"$fastq_name" &>> "${o}"/log/"$fastq_name""_breseq.log"
            
            # In case of two unpaired files
            else
                echo -e "*** IDENTIFY VIRUSES PRESENT (FILTER-IN)\n"
                "$BRESEQ" -r "$DIRDATA"/"${v}".gbk $BRESEQ_OPTIONS -j "$THREADS" "$input_R1_paired_file" "$input_R2_paired_file" "$input_R1_unpaired_file" "$input_R2_unpaired_file" -o "${o}"/output/analysis/"$fastq_name" &>> "${o}"/log/"$fastq_name""_breseq.log"
            fi 
        fi

        # Remove useless dir of breseq output
        rm -r "${o}"/output/analysis/"$fastq_name"/0*

        echo -e "*** REPORT NUMBER OF TOTAL READS ALIGNED AND PERCENT OF READS FROM EACH VIRUS IDENTIFIED\n"
        # Run python script to report percent of reads of interest aligned, according to the treshold, into a table and the number of reads input aligned
        python3 "$DIRSCRIPTS"/write_output_tables.py "$fastq_name" "${o}"/output/analysis/"$fastq_name"/output/summary.json "${o}"/output/evidences/refs.percents.txt "$THRESHOLD" --output_counts "${o}"/output/evidences/filterin.counts.txt

    done

    echo -e "\n------------------  All samples  ---------------------"

    echo -e "*** REPORT COVERAGE FOR EACH VIRUS IDENTIFIED AND RETRIEVE VIRAL READS ALIGNED\n"
    # For each line from the file refs.percents.txt where there are samples and references detected
    while IFS=$'\t' read -r sample reference percent
    do
        # Run samtools to retrieve from sample alignment against reference   
        "$SAMTOOLS" view -@ "$THREADS" -h "${o}"/output/analysis/"$sample"/data/reference.bam "$reference" > "${o}"/tmp/"$sample"_"$reference".sam

        # Calcul metrics about coverage
        "$SAMTOOLS" depth -a "${o}"/tmp/"$sample"_"$reference".sam | awk 'NR==1 {maxcov=0;mincov=1}; NR>1 {sumcov+=$3; if(mincov>$3) mincov=$3; if(maxcov<$3) maxcov=$3; if($3>2) {covmoretwo++}; if($3>20) {covmoretwenty++}; cnt = NR} END {print spl"\t"ref"\t"sumcov/(cnt-1)"\t"mincov"\t"maxcov"\t"covmoretwo"\t"covmoretwenty}' spl="$sample" ref="$reference" >> "${o}"/output/evidences/refs.coverage.txt

        # Retrieve reads aligned and save them into a fastq file
        "$SAMTOOLS" fastq -@ "$THREADS" -0 "${o}"/output/data/filter_in/"$sample"_"$reference".fastq.gz "${o}"/tmp/"$sample"_"$reference".sam  
        rm "${o}"/tmp/"$sample"_"$reference".sam
    done < "${o}"/output/evidences/refs.percents.txt

    # To finalize, add the header to output files
    sed -i '1 i\SAMPLE\tNBR_READS_TO_ALIGN\tNBR_TOTAL_READS_ALIGNED' "${o}"/output/evidences/filterin.counts.txt
    sed -i '1 i\SAMPLE\tREFERENCE\tPERCENT_OF_READS_ALIGNED' "${o}"/output/evidences/refs.percents.txt 
    sed -i '1 i\SAMPLE\tREFERENCE\tAVERAGE_DEPTH\tMIN_DEPTH\tMAX_DEPTH\tBASES_COVERED_AT_LEAST_TWICE\tBASES_COVERED_AT_LEAST_TWENTY_TIMES' "${o}"/output/evidences/refs.coverage.txt
fi

# Remove tmp directory
rm -r "${o}"/tmp/

# Remove unzip reference
if [ -f "$DIRDATA"/"${v}"*.zip ]
then
    rm "$DIRDATA"/"${v}".gbk
fi

echo -e "### SUCCESSFULLY ENDED"
